### ISSUE TITLE
Fix tests

### ISSUE THREAD

**Issue by nickcolley** [nickcolley/jest-axe#104]
Master is failing, will need to sort this for the next release. (Which is breaking).

Travis doesnt seem to be running tests on new pull requests either.

https://travis-ci.org/github/nickcolley/jest-axe

**Comment by mcataford** [comment]
I'd love to give that a look! Will try and throw a PR together tonight and see what can be done here. 🚀

**Comment by mcataford** [comment]
Opened #106 to address this!
