### ISSUE TITLE
React Portal support

### ISSUE THREAD

**Issue by lluia** [nickcolley/jest-axe#105]
First of all, thanks for doing such an amazing job with `jest-axe` 💓 💯 👏🏻

## The issue

We're trying to use `jest-axe` to verify the output of [Reakit components](https://reakit.io/).

Here's the PR that captures the work: https://github.com/reakit/reakit/pull/652

We basically [configured `axe`](https://github.com/reakit/reakit/blob/master/packages/reakit-test-utils/src/axe.ts#L3-L8) to test components on isolation and now we're [trying to verify the HTML output of a component:
```tsx
test("renders with no a11y violations", async () => {
  const { container } = render(<ButtonWithTooltip />);
  const results = await axe(container.innerHTML);

  expect(results).toHaveNoViolations();
  cleanup;
});
```
However, we're facing the following error:
```
["Error: Uncaught [NotFoundError: The node to be removed is not a child of this node.]
        at reportException (/Users/lluis/Code/reakit/node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:62:24)
        at innerInvokeEventListeners (/Users/lluis/Code/reakit/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:346:9)
        at invokeEventListeners (/Users/lluis/Code/reakit/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:281:3)
```
Many **Reakit** components make use of [React Portals](https://reactjs.org/docs/portals.html), and we noticed when we switch off portals ( _through a prop_ ) then the `jest-axe` test pass.

So the question being is this library compatible with portals? 🤔

**Comment by lluia** [comment]
Having another looks at this, the issue might be in our side.

Our custom `<Portal />` component attempts to remove itself from his parent DOM [whenever this one changes](https://github.com/reakit/reakit/blob/master/packages/reakit/src/Portal/Portal.tsx#L35-L41) ( cc. @diegohaz  ) and somehow this conflicts with `jest-axe` [wiping out the DOM](https://github.com/nickcolley/jest-axe/blob/master/index.js#L21-L28) while executing `axe` checks.

**Comment by nickcolley** [comment]
When I put this together I didn't anticipate Portals:
If you can figure out a way around this, we could update the library or add documentation to the README.

**Comment by lluia** [comment]
Thanks @nickcolley, I'll try to have a look and if possible suggest a solution 🤞🏻

**Comment by kennygrubb** [comment]
I was able to test it by using baseElement
const { baseElement } = render(<ButtonWithTooltip />);
const results = await axe(baseElement)

**Comment by nickcolley** [comment]
@kennygrubb is that this? https://testing-library.com/docs/react-testing-library/api#baseelement

**Comment by lluia** [comment]
@nickcolley yup I think he refers to that, @diegohaz explained it [here](https://github.com/reakit/reakit/pull/652#issuecomment-649677575), I guess we're good closing this now 💆🏻‍♂️ 🎊 ( _as it wasn't a problem of the library but how our tests were written_ )

**Comment by nickcolley** [comment]
@lluia what do you think about adding something to the README to explain that?

I'll re-open if you or someone else is interested.

**Comment by lluia** [comment]
@nickcolley yup happy to open a PR adding some small explanation on the `README` 💅🏻 🙌🏼

**Comment by nickcolley** [comment]
Closing this out for now but you're still welcome to add some documentation if you want to in the future, thank you.

**Comment by lluia** [comment]
@nickcolley [here you go](https://github.com/nickcolley/jest-axe/pull/134) 💚
