### ISSUE TITLE
Define impact level

### ISSUE THREAD

**Issue by martiL** [nickcolley/jest-axe#115]
First of all: Great job! 

It would be nice if it were possible to define the impact levels that should be used ("critical", "moderate", "etc.") . 

This axe plugin for cypress does this in a very nice way (see [here](https://github.com/avanslaars/cypress-axe#parameters-on-cychecka11y-axerun) - **includedImpacts**).

**Comment by nickcolley** [comment]
Heya Martin :)

This does sound useful, I wonder if it makes sense as a variation of the jest helper `toHaveNoViolations`...

If someone wanted to give more detail on this feature I can consider a pull request on it. :)

**Comment by martiL** [comment]
I'll take a closer look and create a PR if I find a proper solution :-)

**Comment by nickcolley** [comment]
Released as 4.1.0, thanks :)
