### ISSUE TITLE
Add support for `toHaveNoIncomplete`

### ISSUE THREAD

**Issue by chimericdream** [nickcolley/jest-axe#122]
I came across this when trying to determine the root cause of what I originally thought was a bug. I had a test that I expected to have an aXe failure, but it turns out it is falling into the `incomplete` array of rule checks. I assume the `toHaveNoViolations` matcher essentially checks the for `violations.length === 0`; I'd like to propose a corresponding `toHaveNoIncomplete` matcher which checks the `incomplete` array.

**Comment by nickcolley** [comment]
I think I avoided this because only violations can be counted on to fail in a CI environment as they dont require manual review, but If you'd like this I'd accept a pull request for it.

**Comment by nickcolley** [comment]
Closing old issues out.
