### ISSUE TITLE
How to use without requiring async/await for every render?

### ISSUE THREAD

**Issue by ericrobinsondev** [nickcolley/jest-axe#137]
Hi,

I'd like to use `toHaveNoViolations` in a project to extend expect. 

Is there a way to do this without requiring async/await for every render of my react components? I'd love for it to be transparent to the users of the extended expect.

**Comment by nickcolley** [comment]
Think you'll need to use async/await but if you can give an example that'd help, closing old issues but if this is still something you're interested feel free to re-open with your reply.
