### ISSUE TITLE
axe-core 4.1.1 support

### ISSUE THREAD

**Issue by anthony-kopczyk** [nickcolley/jest-axe#149]
Is there any estimate on an update to the axe-core version/is it actively being worked?

We use this package and have color contrast tests disabled in a few areas due to bugs existing in axe-core. Since axe-core has been updated (and apparently has fixed for those issues), I wanted to make an issue here for tracking.

Thank you for all you've done with this package!

**Comment by anthony-kopczyk** [comment]
Cross referencing the dependabot PR for this.

https://github.com/nickcolley/jest-axe/pull/145

**Comment by nickcolley** [comment]
Publishing a bump to 4.2.1 soon.

**Comment by anthony-kopczyk** [comment]
Just saw this was bumped. Thanks!
