### ISSUE TITLE
Lower the Node engine requirements to 8.x.x

### ISSUE THREAD

**Issue by gcazaciuc** [nickcolley/jest-axe#19]
Hi,

I noticed the minimum required Node version in package.json is 8.9.4. I'm wondering if we can lower this to > 8 since it's seem pretty limiting. Is there something that is present in 8.9.4 and above that is required by this library ?

**Comment by nickcolley** [comment]
Sure thing, will do.

**Comment by nickcolley** [comment]
Released under 2.1.3
