### ISSUE TITLE
"TypeError: (0 , _prettyFormat.format) is not a function" error message from wrong heading order

### ISSUE THREAD

**Issue by isaacalves** [nickcolley/jest-axe#195]
Had this problem recently:

```
  TypeError: (0 , _prettyFormat.format) is not a function

      48 |     const { container } = render(<Wizard />, { wrapper: MockProviders })
      49 |     const result = await axe(container)
    > 50 |     expect(result).toHaveNoViolations()
         |                    ^
      51 | })
```

Found out then that the problem was that the `Wizard` component (which has other nested components) when rendered formed an incorrect sequence of headings: an `<h1>` was rendered and then later on an `<h3>` without an `<h2>` in between.

That error message from axe wasn't very helpful, though. I remember having that issue in the past and getting a helpful error message, [something like this](https://dequeuniversity.com/rules/axe/4.2/heading-order).

Is this a bug?

UPDATE

Although this really seems to be the reason why I got that error, the accessibility test is still flaky. I've run the test 10 times for each of these scenarios:

- with the right heading element: FLAKY (passed 5 out of 10)
- commenting the heading element: ALWAYS PASS (passed 10)
- with the wrong heading element: ALWAYS FAILS (failed 10)

**Comment by nickcolley** [comment]
There's a new version with latest axe that may resolve this, please re-open if you're still running into problems that can be fixed by changing jest-axe.
