### ISSUE TITLE
Clarify which rules are run by default

### ISSUE THREAD

**Issue by agameofprivacy** [nickcolley/jest-axe#197]
Hey folks, apologies for the silly question. 

I looked around, but couldn't confirm which rule sets are run by default if axe is not configured with custom options. In `axe-core`'s docs, it's mentioned that experimental rules are off by default; does that mean _all_ rules [here](https://github.com/dequelabs/axe-core/blob/develop/doc/rule-descriptions.md) but experimental rules are run by default through `jest-axe`?

Thank you.

**Comment by nickcolley** [comment]
The default options are empty by default, so whatever axe-core defaults to jest-axe will share the same defaults.
