### ISSUE TITLE
Adding a configurable error threshold

### ISSUE THREAD

**Issue by dwightjack** [nickcolley/jest-axe#203]
Hi!

At the moment, the matcher passes only when it detects no violations.

Other tools like [pa11y](https://github.com/pa11y/pa11y#threshold-number) and the next version of [cypress-axe](https://github.com/component-driven/cypress-axe/issues/75) allow uses to set a tolerance threshold for the test.

What about adding such a threshold to this matcher as well? If it sounds good to you, I could submit a PR with the related changes.

**Comment by nickcolley** [comment]
I'd recommend instead adding `.skip` to a specific test or telling axe to ignore a certain rule.
