### ISSUE TITLE
Updating Dependency axe-core 4.2.1 to newer version of 4.4

### ISSUE THREAD

**Issue by dafnem1** [nickcolley/jest-axe#206]
https://github.com/nickcolley/jest-axe/blob/6965b7a11eff021d16785f8c70f6ee1cbb64b0a8/package.json#L27

This is a request to update axe-core version.

Currently my project is using jest-axe and axe-core 4.2.* but would like to update to the newer version of axe-core which has newer features, but can't because jest-axe doesn't support it.

**Comment by dafnem1** [comment]
I'm willing to create a PR for this to be fixed :)

**Comment by dafnem1** [comment]
Created a PR for this: https://github.com/nickcolley/jest-axe/pull/212

**Comment by TrevorRice** [comment]
I'd love to see `jest-axe` using the latest version of `axe-core` as well! Looks like [`4.4.1`](https://github.com/dequelabs/axe-core/blob/develop/CHANGELOG.md#441-2022-02-03) is the latest. @dafnem1 — I wonder if it would be worth updating your open MR to pull in `4.4.1`.

**Comment by dafnem1** [comment]
Hi @TrevorRice just updated the PR to `axe-core 4.4.1` :)

**Comment by nickcolley** [comment]
Just publishing a new version with 4.4.1 for you both, thanks for your patience and help.

**Comment by nickcolley** [comment]
Published as 6.0.0 https://www.npmjs.com/package/jest-axe/v/6.0.0

closes #212

**Comment by nickcolley** [comment]
Published version 6 with this updated thanks mate
