### ISSUE TITLE
Update types for latest version

### ISSUE THREAD

**Issue by samatcolumn** [nickcolley/jest-axe#213]
Right now the latest version of `@types/jest-axe` is `3.5.3` which provides types for `jest-axe` v3.5. This is not the latest version of `jest-axe` and it assumes a different major version of `axe-core` which means there are conflicts in the types for `axe.RunOptions`, etc:

```
npm ls axe-core
...
├─┬ @types/jest-axe@3.5.3
│ └── axe-core@3.5.6 
├─┬ jest-axe@5.0.1
│ └── axe-core@4.2.1 
```

**Comment by nickcolley** [comment]
I think that this has been done by community members in the past so I cant help here sorry, if someone wants to update them in the community repos that's fine with me but I wont be maintaining types in this package itself, the API does not change hardly ever breaking changes are nearly always just updating axe-core incase of updated test results so should be minimal effort.

**Comment by samatcolumn** [comment]
@nickcolley that's fair, however you might want to remove the recommendation to install `@types/jest-axe` from the README since it's for version 3.x
