### ISSUE TITLE
Expose just 'toHaveNoViolations' on its own?

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [NickColley/jest-axe#262]
👋 Hi! This package is great and I've been using it for years. Thanks again for making it!

Coming over from https://github.com/dequelabs/axe-core-npm/issues/647: I'd like to get the its error reporting in particular in an environment that runs aXe separately from this package. What do you think about exposing something like the `toHaveNoViolations` matcher so that other environments such as Playwright can use it standalone?

```ts
const results = await new AxeBuilder({ page }).analyze();

expect(results).toHaveNoAxeViolations();
```

Just for fun, I prototyped how this would look here: https://github.com/JoshuaKGoldberg/expect-no-axe-violations. But I'm happy to archive that package if you'd prefer to have `jest-axe` export the utility on its own, or add you as a maintainer to `expect-no-axe-violations`.

**Comment by NickColley** [comment]
This is a cool idea but I'm struggling to see why you cant already use the import just for the part you need without pulling in the axe runner?

**Comment by NickColley** [comment]
Do you mean publish it standalone?

**Comment by JoshuaKGoldberg** [comment]
D'oh! Sorry, I must have been having an off day - I'd thought that `.toHaveNoViolations()` _also_ ran aXe. But looking back through this project's README.md and `index.js`, no, it's just the standalone reporter. Sorry for the noise! I'll archive my project and just use this one directly. 🤦
