### ISSUE TITLE
Doesn't seem to work with fake timers

### ISSUE THREAD

**Issue by asperkin** [NickColley/jest-axe#263]
Our tests are designed to work with fake timers, but this code: 

```
const results = await axe(element);
  expect(results).toHaveNoViolations();
```
 results in this error with fake timers.

```
Error: thrown: "Exceeded timeout of 5000 ms for a testfalse.
Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."
```

We created a helper that wraps this with a timer system change.

```
jest.useRealTimers();
  const results = await axe(element);
  expect(results).toHaveNoViolations();
  jest.useFakeTimers();
```

However, the tests are inconsistently timing out with this (perhaps due to running in parallel), so it doesn't feel perfect. Not sure how to proceed.

**Comment by NickColley** [comment]
https://github.com/NickColley/jest-axe/pull/266
