### ISSUE TITLE
Possible typo in the README

### ISSUE THREAD

**Issue by hhaidar** [NickColley/jest-axe#267]
Hello,

The README states:

> The GDS Accessibility team found that only [~30% of issues are found by automated testing](https://accessibility.blog.gov.uk/2017/02/24/what-we-found-when-we-tested-tools-on-the-worlds-least-accessible-webpage).

But the blog post states:

> While the tools picked up the majority of the accessibility barriers we created – 71% – there was a large minority that would only have been picked up by manual checking.

Should the README be changed to say that "~70% of issues are found by automated testing"?

Apologies if I misread or missed anything.

**Comment by NickColley** [comment]
https://alphagov.github.io/accessibility-tool-audit/index.html

At best 40%
