### ISSUE TITLE
Specify rules for specific selectors

### ISSUE THREAD

**Issue by nick-ollier** [NickColley/jest-axe#269]
Hello 👋🏼

I'm not sure if this exists as I can't find it in the documentation anywhere.  If not, I'm open to taking a look if it's something you'd be interested in adding to `jest-axe`...?

**🤕 The Problem:**
Our internal UI team have introduced an accessibility issue that's unfortunately not due to be resolved for a few months.  We have recently inherited this issue via a mandatory package update meaning our accessibility tests are now failing.

We're currently disabling this rule across the codebases we look after -  However, there is a concern that disabling the rule entirely may result in us missing unexpected violations for the same rule elsewhere.

**🤔 Potential Solution:**
I'm wondering if it would be reasonable to add the ability to pass an optional array of selectors to be excluded for each rule? 

Using the below as reference and assuming the above solution is in place - the `label` rule will be ignored for `input` 1, 2 & 3, however, the test will still throw an accessibility violation error because `data-testid="i-should-still-fail` is not excluded.

**🚨 MVP - Inputs with no label:**
```js
it("should have no accessibility violations", async () => {
    const { container } = render(
        <div>
            <input type="text" id="ignore-me" />
            <input type="text" className="ignore-me" />
            <input type="text" data-testid="ignore-me" />
            <input type="text" data-testid="i-should-still-fail" />
        </div>
    );

    const results = await axe(container, {
        rules: {
            label: {
                enabled: false,
                exclude: ['#ignore-me', '.ignore-me', '[data-testid="ignore-me"]'],
            },
        },
    });

    expect(results).toHaveNoViolations();
});
```

**Comment by NickColley** [comment]
Check the axe-core documentation they highlight how to exclude parts of the page:

https://github.com/dequelabs/axe-core/blob/master/doc/API.md#parameters-axerun

```js
axe.run(
  {
    exclude: '.ad-banner'
  },
  (err, results) => {
    // ...
  }
);
```

You can then pass this to the jest-axe constructor, if you run into issues feel free to re-open.

**Comment by nick-ollier** [comment]
Thanks @NickColley!

I'll try that out :)

**Comment by nick-ollier** [comment]
Hey @NickColley - I'm not sure I'm fully understanding what to do here...  I have an example, but I'm not too sure what to do with `axe.run`?

```jsx
import React from "react";
import { render } from "@testing-library/react";
import { axe } from "jest-axe";
import * as axeCore from "axe-core";

const BadInput = () => (
	<div>
		<input type="text" id="ignore-me" />
	</div>
);

it("should have no accessibility violations", async () => {
	const { container } = render(<BadInput />);

	const axeCoreOptions = await axeCore.run(
		{
			exclude: "#ignore-me",
		},
		(error, results) => {}
	);

	const results = await axe(container, axeCoreOptions);

	expect(results).toHaveNoViolations();
});

```

Thanks again :)

**Comment by nick-ollier** [comment]
> take a look at https://github.com/NickColley/jest-axe#axe-configuration for how to pass options

Ah, sorry @NickColley - I have tried this, but it doesn't seem to work? I'm probably missing something really obvious here... 

Disabling the rule as a whole works as I'd expect it to.  But I just can't seem to disable rule(s) for specific selectors?

To give you a closer example of what we're trying to resolve - 
- `ExternalInputComponent` breaks the axe label rule (assume this comes from an external library).
- `InteralInputComponent` does not break the axe label rule (assume this is built within the project repo).
- Disabling the rule using `{ rules: { label: { enabled: false } } }` works fine, and right now isn't a problem.
- However, the concern is, if someone was to change our `InteralInputComponent`, removing the label, our a11y tests won't pick it up, allowing the test to pass.

I'm not sure if the question here is around excluding or including selectors.  I think it maybe makes more sense to enable a rule for a specific selector rather than disable it for potentially many selectors?

Does this make sense?

Sorry if I'm being a pain - Just struggling to wrap my head around this one - I appreciate your help!!

```jsx
import React from "react";
import { render } from "@testing-library/react";
import { axe } from "jest-axe";

const ExternalInputComponent = () => <input type="text" id="external-input" />;
const InternalInputComponent = (props) => (
	<label htmlFor="internal-input">
		Input Label:
		<input type="text" id="internal-input" {...props} />
	</label>
);

const ExampleForm = () => (
	<form>
		<ExternalInputComponent />
		<InternalInputComponent />
	</form>
);

it("should have no accessibility violations", async () => {
	const { container } = render(<ExampleForm />);

	const results = await axe(container,{
        rules: {
            label: {
                enabled: false,
                exclude: "#internal-input", // maybe not the best approach?
                include: "#external-input" // only disable the rule for offending selectors may be best?
            },
        },
    });

	expect(results).toHaveNoViolations();
});
```
