### ISSUE TITLE
Update axe-core to latest

### ISSUE THREAD

**Issue by hpinkos** [NickColley/jest-axe#270]
I'm currently running into this bug: https://github.com/dequelabs/axe-core/issues/3771

It looks like it was fixed in https://github.com/dequelabs/axe-core/pull/3777 and included in the `4.5.2` release.
Can you please update your dependencies to help us fix this issue?  Thanks!

**Comment by philcon93** [comment]
I'm also needing the latest axe-core in our code base, I have created a PR which would update this dependency if we could get that looked at please :) 

- https://github.com/NickColley/jest-axe/pull/272

**Comment by NickColley** [comment]
Okay the newer version of axe fails as it's expecting the existence of canvas, so I need to determine what rule is using canvas and decide if it's worth adding this additional dependency to the instructions or by default turning off this rule.

**Comment by NickColley** [comment]
They've introduced more color checks which is disabled by default in jest-axe, so I've added functionality to find color category rules and auto disabled them by default:

https://github.com/NickColley/jest-axe/pull/273/commits/21b41602d052249b07c4b06221319500fc12552a

**Comment by NickColley** [comment]
Released as jest-axe version 8
