### ISSUE TITLE
Questions About the Use of jest-axe

### ISSUE THREAD

**Issue by clutzhat** [NickColley/jest-axe#275]
Hi Nick,

I wanted to see if you would be able to provide me with some information on the use of jest-axe for running automated accessibility testing in the dev environment.

I have outlined my questions in the following google doc. https://docs.google.com/spreadsheets/d/1MvqPDx9CZMGDYZFf_FQbCjytSINRqRSNpQxsjGfzBPE/edit#gid=123605610
 
Would greatly appreciate any feedback you may have (in column B).

Thanks so much in advance.

Christina Lutz-Hatfield

Digital Services | City and County of San Francisco

**Comment by NickColley** [comment]
Hello, your spreadsheet is private so I cannot see the questions.

Please copy your questions into GitHub, it is important that questions are asked here instead of in Google sheets so others can find them using Google.

**Comment by clutzhat** [comment]
Hi Nick,

Thanks so much for your quick reply. Really appreciate it.

I have made the spreadsheet accessible to anyone. 
https://docs.google.com/spreadsheets/d/1MvqPDx9CZMGDYZFf_FQbCjytSINRqRSNpQxsjGfzBPE/edit#gid=123605610 

Also, following are all the questions that I have. 

Would we have the ability on our end to configure/customize the validation to a) check against all Level AA guidelines b) and only specific Level AAA guidelines?

Is jest-axe using all the axe-core rules https://github.com/dequelabs/axe-core/blob/f0292714b94a1483f4148f3ca7206897cfb21318/doc/rule-descriptions.md#readme ?

Does jest-axe have the ability to create and run custom rules? (For example to screen out false positives)

Will jest-aze fully integrate with any dev environment? Wagtail, form.io

Does jest-axe include APIs so that you can run automated accessibility tests alongside other automated unit tests (CI/CD/CLI integration)?

Would you be able to describe how jest-axe is integrated to the pipeline?

Does jest-axe allow for both linting and self written tests?

Does jest-axe have the ability to test and validate for keyboard only interactions? 

Is jest-axe able to test against all keyboard interactions mentioned in our accessibility guide https://sfgovdt.jira.com/wiki/spaces/SFGOV/pages/1917157446/Keyboard+Accessibility  and for the most common keyboard interactions as outlined here https://sfgovdt.jira.com/wiki/spaces/SFGOV/pages/1917157453/Testing+for+Keyboard+Accessibility  ? 

Would jest-axe have been able to identify the keyboard related issues listed here https://docs.google.com/document/d/1JDbKyN5-N3NRe83FzuIINsigUjEkiSYAy_JUdl-D5m8/edit   and here https://docs.google.com/document/d/1fOrkof81NiUC6RaZifSzPerMdq4b5_IHAtuU_NeLVus/edit that I was able to identify by completing a manual keyboard only test?.

Does jest-axe have the ability to test multi page dynamic forms? Does it integrate with form.io? Would jest-axe have been able to identify the accessibility issues that I was able to identify here https://docs.google.com/document/d/1HpYw1RmB6TYu5p-T8hvk9dMQsSLKx2ywJWIJfdD3-qQ/edit#heading=h.bnd3yefmnmc9  across our dynamic forms by performing manual keyboard only and screen reader testing?

Does jest-axe have the ability to create and integrate scripts for user flow testing?

Does jest-axe have the ability to test keyboard only interaction and navigation within, for example, a calendar widget or a modal window? Would jest-axe have been able to identify the keyboard related issues listed here https://docs.google.com/document/d/1JDbKyN5-N3NRe83FzuIINsigUjEkiSYAy_JUdl-D5m8/edit  and here https://docs.google.com/document/d/1fOrkof81NiUC6RaZifSzPerMdq4b5_IHAtuU_NeLVus/edit   that I was able to identify by completing a manual keyboard only test?

Will jest-axe return detailed information on accessibility violations and how to fix them?  Will it provide a report with issues that can easily be shared with other engineers or non-engineers? What type of format would the report be in?

Does jest-axe trigger false positives? Does it flag "potential" issues that you would have to manually identify if it's a true violation?

Does jest-axe have APIs that can integrate into CMS publishing workflows such as Wagtail?

**Comment by NickColley** [comment]
A lot of these questions can be resolved by doing some reading of the documentation and exploring this yourself. Please respect my time and only ask questions when you have exhausted your own research options.

Closing this out, only re-open with questions that you have been unable to answer yourself after spending the time to read the documentation and trying the project put (technical spike).
