### ISSUE TITLE
Simple "valid" form being reported as invalid

### ISSUE THREAD

**Issue by michaelryancaputo** [nickcolley/jest-axe#57]
I have recreated the issue i'm seeing here: https://codesandbox.io/s/jn781kl4zy?codemirror=1&fontsize=14

For some reason this very basic form example is not valid using the `jest-axe` plugin. I have validated that this test should pass using the aXe inline validation playground.

**Comment by nickcolley** [comment]
I wonder if this is the same issue as https://github.com/nickcolley/jest-axe/issues/56 given they're both related to duplicate IDs?

Thank you for raising, when I get some time I'll try to investigate this.

**Comment by nickcolley** [comment]
I believe this is the same as https://github.com/nickcolley/jest-axe/issues/56#issuecomment-520236150 so will close out, feel free to re-open if 3.2.0 release does not resolve your issues.
