### ISSUE TITLE
Question: react-test-renderer

### ISSUE THREAD

**Issue by donifer** [nickcolley/jest-axe#60]
Can this be used with `react-test-renderer`? I'm assuming no but just double checking. Thanks

**Comment by nickcolley** [comment]
I looks like react-test-renderer does not render to the DOM so it wont work with this library

> This package provides an experimental React renderer that can be used to render React components to pure JavaScript objects, without depending on the DOM or a native mobile environment.

If you find out otherwise lemme know, closing this out :)

**Comment by RyanPWalker** [comment]
I just tried it, it doesn't work.  Throws the error `html parameter should be an HTML string or an HTML element`
It would be cool if it did, but till then I think [react-testing-library](https://medium.com/hackernoon/testing-react-with-jest-axe-and-react-testing-library-accessibility-34b952240f53) is the best choice.
