### ISSUE TITLE
Fails to check full html document

### ISSUE THREAD

**Issue by tonianelope** [nickcolley/jest-axe#65]
I'm trying to test the accessibility of the document. 

`expect(await axe(document.documentElement.outerHtlm)).toHaveNoViolations()` does not produce the expected violations, even if you pass is an obviously faulty string (e.g a document without title it isn't flagged, though it is mentioned in the [axe-core docs](https://github.com/dequelabs/axe-core/blob/a1eb245434228d21164c60341b3ee0a0d05a4c07/doc/rule-descriptions.md))

Does jest-axe not support the full functionality of axe-core?

**Comment by dakebl** [comment]
Hey @tonianelope , 

Could you post a larger code snippet, with your imports in too, as it's hard to debug without more info.

A couple of things though:

- You have a typo `outerHtlm` should be `outerHTML`

- You should probably move your await out of the expect:
```js
test('accessibility ', async () => {
  const html = await axe(document.documentElement.outerHTML);
  expect(html).toHaveNoViolations();
});
```

**Comment by nickcolley** [comment]
Without the full steps to reproduce I can't try and help you figure out this problem, so going to close this for now, please re-open with more detail and we'll try and figure this out :)
