### ISSUE TITLE
small typo README.md 'Testing React with Enzyme'

### ISSUE THREAD

**Issue by lgibso34** [nickcolley/jest-axe#77]
sorry i do not know how to do a multiline code block

`const wrapper = mount(<App/>)`
` const results = await axe(container.getDOMNode())`

should be

`const wrapper = mount(<App/>)`
`const results = await axe(wrapper.getDOMNode())`

Also I had to change
`const App = require('./app')`

to

`import App from '.App'`

because mount was being passed an object instead of the component

**Comment by nickcolley** [comment]
Fixed thanks for raising this issue!
