### ISSUE TITLE
toHaveNoViolations does not exist on type Matchers<any> typescript

### ISSUE THREAD

**Issue by code-mattclaffey** [nickcolley/jest-axe#79]
I get the following error when trying to get this working with ts-jest:

```
TypeScript diagnostics (customize using `[jest-config].globals.ts-jest.diagnostics` option):
    src/components/PriceBreakdown/components/ChargesList/ChargesList.test.tsx:124:19 - error TS2339: Property 'toHaveNoViolations' does not exist on type 'Matchers<any>'.
```

I am following the documentation correctly so I was just wondering if there is any documentation around using this with typescript.

example of how I am using it:

```
import { axe, toHaveNoViolations } from "jest-axe";

expect.extend(toHaveNoViolations);

it("should be accessible", async () => {
         // wrap is just a react component
	const { container } = wrap([fee1, fee2, fee3], "Some text", true);
	const results = await axe(container);
	expect(results).toHaveNoViolations();
});
```

**Comment by code-mattclaffey** [comment]
```
interface ExtendedMatchers extends jest.Matchers<toHaveNoViolations> {
	toHaveNoViolations(): toHaveNoViolations;
}

(expect(results) as ExtendedMatchers).toHaveNoViolations();
```

This seem to be the pattern people follow for other functions but I am unable to get it working. Probably because I am not very good at typescript.

**Comment by hernandezbb** [comment]
I had the same problem. I fixed it with `npm i -D @types/jest-axe`

**Comment by nickcolley** [comment]
I wonder if we should add @hernandezbb 's advice to the README?

**Comment by tyq340503** [comment]
same issue, npm i -D @types/jest-axe works fine for me

**Comment by nickcolley** [comment]
Thanks to @hernandezbb we now have some instructions for typescript folks, so hopefully this will help people. Please re-open if this is not the case.

**Comment by ogomez-at-wiris** [comment]
Still does not work for me even though I installed @types/jest-axe... Getting the same error as original poster.

**Comment by josectobar** [comment]
Same situation for me. I already installed `@types\jest-axe`

**Comment by josectobar** [comment]
> Same situation for me. I already installed `@types\jest-axe`

nevermind, I forgot. to add `expect.extend(toHaveNoViolations);`

**Comment by fullhdpixel** [comment]
I still have this issue:

```
import { render } from "@testing-library/react";
import "@testing-library/jest-dom";
import { expect, it } from "@jest/globals";

const { axe, toHaveNoViolations } = require("jest-axe");
expect.extend(toHaveNoViolations);


describe("Components", () => {
  it("finds no a11y violations", async () => {
    const { container } = setup({});
    const results = await axe(container);

    expect(results).toHaveNoViolations();
  });
});
```

`Property 'toHaveNoViolations' does not exist on type 'Matchers<void> & SnapshotMatchers<void, any> & Inverse<JestMatchers<void, any>> & PromiseMatchers<any>'. typescript (2339) [29, 21]`

**Comment by thijssmudde** [comment]
Anyone have a clue? I've installed @types/jest-axe and also added `expect.extend(toHaveNoViolations);` to the test file.

**Comment by savchukm** [comment]
@thijssmudde @code-mattclaffey Surprisingly I am able to fix the original issue in following way:
```ts
import 'jest-axe/extend-expect'
import { axe } from 'jest-axe';
```
