### ISSUE TITLE
Breaking changes on 3.4

### ISSUE THREAD

**Issue by obartra** [nickcolley/jest-axe#92]
Hi there, thanks for your work on jest-axe!

I just upgraded to 3.4 and I'm getting the following error (I suspect related to the axe update):

```sh
 "All page content must be contained by landmarks (region)"
```

I can set up a global config as you suggest on the readme but I was wondering if it would make sense to disable this rule by default on unit tests

**Comment by nickcolley** [comment]
Perhaps we should always do a breaking release when we bump axe instead.

**Comment by nickcolley** [comment]
In future, I will do major releases for axe bumps that include rule changes, sorry for the inconvenience here, if anyone needs me to release a patch version to restore backwards compatibility let me know.

Right now, you could set a global configuration to opt out of this if you're testing components in isolation.

```js
const { configureAxe } = require('jest-axe')

const axe = configureAxe({
  rules: {
    // disabled landmark rules when testing isolated components.
    'region': { enabled: false }
  }
})
```

https://github.com/nickcolley/jest-axe#setting-global-configuration

Thanks for your patience with breaking your build!
