### ISSUE TITLE
Getting `act` warnings running axe 

### ISSUE THREAD

**Issue by James-Reed-cognito** [nickcolley/jest-axe#95]
We are using axe as described in the readme and other examples we've looked at online and are getting `act` warnings when using it.

Expected: Can run axe on react code and assert on violations without `act` warnings
Actual: `act` warnings output to the console when test is run

Example code:

```
describe('tests', () => {
  it('should have no Axe violations', async () => {
    const { container } = render(<MyComponent />);
    const results = await axe(container);
    expect(results).toHaveNoViolations();
  })
});
```

I'm having to wrap the last two lines in act:
```
await act(async () => {
  const results = await axe(container);
  expect(results).toHaveNoViolations();
})
```

In order not to get warnings. I'm not sure how axe is implemented under the hood, so I can't offer much advice, but I do know that react testing library wraps most or all of its actions in `act` calls under the hood - maybe jest-axe needs to do the same with whatever it's doing?

**Comment by nickcolley** [comment]
I think it'd make sense to update the readme and tests if necessary but we dont ship jest-axe with any specific integration for frontend frameworks.

**Comment by James-Reed-cognito** [comment]
I can understand that, and perhaps that's all that's needed. Can I get an understanding of _why_ axe is needing `act` to wrap it? What's it doing that it needs it?

**Comment by nickcolley** [comment]
This is less an issue with axe and more with how React works I think.

> To prepare a component for assertions, wrap the code rendering it and performing updates inside an act() call. This makes your test run closer to how React works in the browser.

https://reactjs.org/docs/test-utils.html#act

So I presume it's React pushing you to use act, but I can't be certain of why without you sharing the specific error warning. Let me know.

**Comment by James-Reed-cognito** [comment]
It's just the standard act warning:
```
console.error node_modules/react-dom/cjs/react-dom.development.js:530
    Warning: An update to MyComponent inside a test was not wrapped in act(...).

    When testing, code that causes React state updates should be wrapped into act(...):

    act(() => {
      /* fire events that update state */
    });
    /* assert on the output */

    This ensures that you're testing the behavior the user would see in the browser. Learn more at https://fb.me/react-wrap-tests-with-act
        in MyComponent
```

I'm literally doing the code I've pasted in the issue description, save that I've subbed out the name of my component.

**Comment by James-Reed-cognito** [comment]
Actually, never mind, you can close this. I've just tried the same code but without the calls to axe and I still get the act warnings - and when I put an empty `await act(() => {})` they go away. It's clearly an issue on my end, and not with axe. Apologies.

**Comment by nickcolley** [comment]
No worries, if you do run into any improvements we can make to the documentation on this let me know. Someone else might run into this and your feedback will be very helpful anyway, have a nice day.

**Comment by GriffinSauce** [comment]
Just wanted to share for others landing here; I had a similar issue in a Next.js project that is related to the `Link` component, but became visible through axe. The solution is currently in an [open PR](https://github.com/vercel/next.js/pull/20) so this is a workaround:

```
// Prevent act() error logs from Link
// TODO: clean up when fixed: https://github.com/vercel/next.js/pull/20169
jest.mock('next/link', () => ({ children }) => children);
```
